ZSH=$HOME/.oh-my-zsh

ZSH_THEME="jwatson2"

plugins=(gem git git-prompt golang marked2 npm tmux vi-mode better-virtualenv)

source $ZSH/oh-my-zsh.sh

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

export VISUAL=nvim
export EDITOR="$VISUAL"

# Colorize BSD ls.
export CLICOLOR=1
export LSCOLORS="exgxcxdxcxegedabagacad"

# Source additional config files.
for config_file (~/.config/zsh/*.zsh) source $config_file

# Load chruby if available
if [[ -e /usr/local/opt/chruby ]]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
fi
