alias art='cd $HOME/projects/Nuance/ACI/artemis'
alias be='bundle exec'
alias cat='bat --style=plain'
alias cb='cargo build'
alias co='git branch | cut -c 3- | fzy | xargs git checkout'
alias cr='cargo run'
alias deadbranches='git branch -vv | grep ": gone]"|  grep -v "\*" | awk "{ print $1;  }" | gxargs -r git branch -d'
alias dirs='dirs -v'
alias grep='rg'
alias ll='ls -l'
alias ls='exa'
alias pcat='pygmentize -f terminal16m -O style=native -g'
alias rstbk='rustup docs --book'
alias simdir='pushd $HOME/Library/Developer/CoreSimulator/Devices'
alias simreset='xcrun simctl erase all'
alias start='vim ~/Documents/notes/day-start-checklist.md'
alias t='exa -T --git-ignore'
alias urna='cd $HOME/projects/Nuance/ACI/Urania'
alias yr='yarn run'
