#!/bin/bash

# Colorize GNU ls.
[[ $PLATFORM == "linux" ]] && alias ls="ls --color=auto"

alias la="ls -hasF"
alias ll="ls -l"
alias lh="ls -sh"
alias pd="perldoc -f"
alias bc="bc -lq"
alias senv="env | sort | less"
alias dirs="dirs -v"
