#!/bin/bash


prompt()
{
    MYPWD=`echo $PWD | sed "s/\/Users\/$USER/\~/"`
    echo -ne '\033]0;'$HOSTNAME : $USER'@'$MYPWD''/' \007'
    unset MYPWD
}

update_terminal_cwd()
{
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
}

# Mimic the csh version of export.
setenv()
{
    eval $1=\"$2\"
    export $1
}

# Make a time-stamped directory
mktsd()
{
    case $OSTYPE in
    linux-gnu)
        mkdir `date --iso-8601=minutes`
        ;;

    *)
        mkdir `date +"%Y-%m-%dT%H:%M%z"`
        ;;
    esac
}

ctags_this()
{
    find * -type d -exec dirtags {} \;
    ctags --file-scope=no -R
}

pycheck()
{
    FILES=$(git status -uno --porcelain | grep .py | awk '{print $2}')
    pep8 $FILES
    pyflakes $FILES
}

pypkg()
{
    mkdir $1
    touch $1/__init__.py
}


# Switch AWS credentials.
aws_creds()
{
    if [ -f ~/.awskeys/$1 ]; then
        echo -e "Switching to \033[33m$1\033[0m AWS credentials."
        . ~/.awskeys/$1
    else
        echo -e "\033[31mUnknown credentials.\033[0m"
    fi
}


# Quick way to rebuild the Launch Services database and get rid
# of duplicates in the Open With submenu.
# Modified from
# http://www.leancrew.com/all-this/2013/02/getting-rid-of-open-with-duplicates/
fixopenwith()
{
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
}


# For use with autoenv. Assumes virtualenvwrapper.
use_env() {
  typeset venv
  venv="$1"
  if [[ `basename "${VIRTUAL_ENV:t}"` != "$venv" ]]; then
    if workon | grep $venv > /dev/null; then
      workon "$venv"
    else
      echo -n "Create virtualenv $venv now? (Yn) "
      read answer
      if [[ "$answer" == "Y" ]]; then
        mkvirtualenv "$venv"
      fi
    fi
  fi
}
