#!/bin/bash

# If Postgres.app is installed, add its binaries to our path.
#if [ -d /Applications/Postgres.app/Contents/MacOS/bin ]; then
#    PGPATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
#else
#    PGPATH=$PATH
#fi

export PATH="~/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export NODE_PATH="/usr/local/share/npm/lib/node_modules"

# Activate my virtualenv.
[[ -s ~/.venv/bin/activate ]] && source ~/.venv/bin/activate

# Enable RVM
[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
