#!/bin/bash

# If Postgres.app is installed, add its binaries to our path.
#if [ -d /Applications/Postgres.app/Contents/MacOS/bin ]; then
#    PGPATH="/Applications/Postgres.app/Contents/MacOS/bin:$PATH"
#else
#    PGPATH=$PATH
#fi

export PATH="~/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export NODE_PATH="/usr/local/share/npm/lib/node_modules"

# Add npm to the path if it is installed.
[[ -s /usr/local/share/npm ]] && export PATH="$PATH:/usr/local/share/npm/bin"

# Add heroku to the path if the toolbelt is installed.
[[ -s /usr/local/heroku ]] && export PATH="$PATH:/usr/local/heroku/bin"

# Enable RVM
[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
